"""
Opportunity scoring engine — produces a 0–100 score for each deal.

Score components and weights:
  ROI              25%  — the financial return
  Demand           25%  — sales velocity (monthly sales estimate)
  Competition      20%  — number of sellers fighting for the buy box
  Reviews          10%  — social proof that the product sells reliably
  Price stability  10%  — Amazon price hasn't been crashing (avoid traps)
  Community        10%  — HotUKDeals temperature/votes (pre-validated demand)

Confidence level:
  very_high  ≥ 85  All signals strong, enrichment from Keepa
  high       ≥ 70  Good signals across the board
  medium     ≥ 50  Mixed signals — worth monitoring
  low        < 50  Weak signals — likely not profitable

The AI narrative (score_reasoning) is generated by Claude and provides
human-readable justification for the score. It runs asynchronously so it
never blocks the scoring pipeline.
"""
from dataclasses import dataclass
from typing import Optional

from app.core.config import settings
from app.core.logging import get_logger
from app.db.models.deal import Deal
from app.services.enrichment.amazon import EnrichedProduct
from app.services.scoring.profitability import ProfitabilityResult

logger = get_logger(__name__)


@dataclass
class ScoreComponents:
    roi: float            # 0–25
    demand: float         # 0–25
    competition: float    # 0–20
    reviews: float        # 0–10
    price_stability: float  # 0–10
    community: float      # 0–10

    @property
    def total(self) -> int:
        return round(
            self.roi + self.demand + self.competition
            + self.reviews + self.price_stability + self.community
        )

    @property
    def confidence_level(self) -> str:
        t = self.total
        if t >= 85:
            return "very_high"
        elif t >= 70:
            return "high"
        elif t >= 50:
            return "medium"
        else:
            return "low"


@dataclass
class ScoringResult:
    score: int
    confidence_level: str
    components: ScoreComponents
    reasoning: str
    tags: list[str]


class OpportunityScoringEngine:
    """
    Computes opportunity score from profitability result + Amazon product data.
    Designed to be called per-deal after enrichment completes.
    """

    async def score(
        self,
        deal: Deal,
        amazon: EnrichedProduct,
        profit: ProfitabilityResult,
    ) -> ScoringResult:
        components = self._compute_components(deal, amazon, profit)
        tags = self._extract_tags(deal, amazon, profit, components)
        reasoning = self._build_reasoning(deal, amazon, profit, components, tags)

        logger.info(
            "deal_scored",
            deal_id=deal.id,
            score=components.total,
            confidence=components.confidence_level,
        )

        return ScoringResult(
            score=components.total,
            confidence_level=components.confidence_level,
            components=components,
            reasoning=reasoning,
            tags=tags,
        )

    def _compute_components(
        self,
        deal: Deal,
        amazon: EnrichedProduct,
        profit: ProfitabilityResult,
    ) -> ScoreComponents:

        return ScoreComponents(
            roi=self._score_roi(profit.roi_percent),
            demand=self._score_demand(amazon.estimated_monthly_sales, amazon.sales_rank),
            competition=self._score_competition(
                amazon.buy_box_seller_count,
                amazon.is_amazon_selling,
                amazon.fba_seller_count,
            ),
            reviews=self._score_reviews(amazon.review_count, amazon.review_rating),
            price_stability=self._score_price_stability(
                amazon.current_price,
                amazon.lowest_price_30d,
                amazon.highest_price_30d,
            ),
            community=self._score_community(deal.hot_score, deal.comment_count),
        )

    # ── Component scorers ─────────────────────────────────────────────────────

    def _score_roi(self, roi_percent: float) -> float:
        """
        ROI → 0–25 points.
        <10%  → 0   (not worth it)
        20%   → 10  (minimum viable)
        40%   → 18
        60%   → 22
        80%+  → 25  (excellent)
        """
        if roi_percent < 10:
            return 0.0
        elif roi_percent < 20:
            return _lerp(roi_percent, 10, 20, 0, 8)
        elif roi_percent < 40:
            return _lerp(roi_percent, 20, 40, 8, 18)
        elif roi_percent < 60:
            return _lerp(roi_percent, 40, 60, 18, 22)
        else:
            return min(25.0, _lerp(roi_percent, 60, 100, 22, 25))

    def _score_demand(
        self,
        monthly_sales: Optional[int],
        sales_rank: Optional[int],
    ) -> float:
        """
        Demand → 0–25 points.
        Based on estimated monthly sales (derived from BSR).
        <5    → 0   (nobody buys this)
        10    → 8
        50    → 15
        200   → 20
        500+  → 25
        """
        if not monthly_sales:
            if not sales_rank:
                return 5.0  # Unknown but not zero
            # Penalise very high rank (slow seller)
            if sales_rank > 500_000:
                return 2.0
            return 8.0

        if monthly_sales < 5:
            return 0.0
        elif monthly_sales < 10:
            return _lerp(monthly_sales, 5, 10, 2, 8)
        elif monthly_sales < 50:
            return _lerp(monthly_sales, 10, 50, 8, 15)
        elif monthly_sales < 200:
            return _lerp(monthly_sales, 50, 200, 15, 20)
        elif monthly_sales < 500:
            return _lerp(monthly_sales, 200, 500, 20, 23)
        else:
            return 25.0

    def _score_competition(
        self,
        seller_count: Optional[int],
        is_amazon_selling: bool,
        fba_seller_count: Optional[int],
    ) -> float:
        """
        Competition → 0–20 points.
        Amazon selling = bad (almost never win buy box).
        Many FBA sellers = hard to compete.
        """
        if is_amazon_selling:
            return 2.0  # Amazon almost always wins buy box

        count = fba_seller_count or seller_count or 0

        if count == 0:
            return 20.0  # No competition — excellent
        elif count == 1:
            return 18.0
        elif count <= 3:
            return 15.0
        elif count <= 5:
            return 12.0
        elif count <= 10:
            return 8.0
        elif count <= 20:
            return 5.0
        else:
            return 2.0

    def _score_reviews(
        self,
        review_count: Optional[int],
        review_rating: Optional[float],
    ) -> float:
        """
        Reviews → 0–10 points.
        Sweet spot: 50–500 reviews at 4.0+ stars.
        Too few = unproven. Too many = saturated / Amazon may be selling.
        """
        if not review_count:
            return 3.0  # New/unknown product

        # Review count component (0–6)
        if review_count < 10:
            count_score = 2.0
        elif review_count < 50:
            count_score = 4.0
        elif review_count < 500:
            count_score = 6.0
        elif review_count < 2000:
            count_score = 5.0
        else:
            count_score = 3.0  # Very established — likely competitive

        # Rating component (0–4)
        if not review_rating:
            rating_score = 2.0
        elif review_rating >= 4.5:
            rating_score = 4.0
        elif review_rating >= 4.0:
            rating_score = 3.5
        elif review_rating >= 3.5:
            rating_score = 2.5
        else:
            rating_score = 1.0

        return min(10.0, count_score + rating_score)

    def _score_price_stability(
        self,
        current_price: Optional[float],
        lowest_30d: Optional[float],
        highest_30d: Optional[float],
    ) -> float:
        """
        Price stability → 0–10 points.
        Volatile prices are a trap — if Amazon drops price, your ROI evaporates.
        Stable prices = safer investment.
        """
        if not current_price or not lowest_30d or not highest_30d:
            return 5.0  # Unknown — give neutral score

        price_range_pct = ((highest_30d - lowest_30d) / lowest_30d) * 100
        # How much has the price dropped from high to current?
        drop_from_high_pct = ((highest_30d - current_price) / highest_30d) * 100

        # Large price drop = danger signal
        if drop_from_high_pct > 30:
            return 2.0  # Price is crashing
        elif drop_from_high_pct > 15:
            return 5.0

        # High range = volatile
        if price_range_pct < 5:
            return 10.0  # Very stable
        elif price_range_pct < 15:
            return 8.0
        elif price_range_pct < 30:
            return 5.0
        else:
            return 2.0  # Highly volatile

    def _score_community(
        self,
        hot_score: Optional[int],
        comment_count: Optional[int],
    ) -> float:
        """
        Community signals → 0–10 points.
        HotUKDeals temperature is a validated proxy for consumer demand.
        High temperature + high comments = deal community has pre-validated this.
        """
        score = 0.0

        # Hot score (0–7)
        if hot_score:
            if hot_score >= 500:
                score += 7.0
            elif hot_score >= 200:
                score += 6.0
            elif hot_score >= 100:
                score += 5.0
            elif hot_score >= 50:
                score += 3.0
            else:
                score += 1.0

        # Comment count (0–3) — engagement signal
        if comment_count:
            if comment_count >= 50:
                score += 3.0
            elif comment_count >= 20:
                score += 2.0
            elif comment_count >= 5:
                score += 1.0

        return min(10.0, score)

    # ── Tags and reasoning ────────────────────────────────────────────────────

    def _extract_tags(
        self,
        deal: Deal,
        amazon: EnrichedProduct,
        profit: ProfitabilityResult,
        components: ScoreComponents,
    ) -> list[str]:
        """Generate descriptive tags for filtering/display."""
        tags = []

        if profit.roi_percent >= 50:
            tags.append("high-roi")
        elif profit.roi_percent >= 30:
            tags.append("good-roi")

        if amazon.estimated_monthly_sales and amazon.estimated_monthly_sales >= 200:
            tags.append("fast-seller")
        elif amazon.estimated_monthly_sales and amazon.estimated_monthly_sales >= 50:
            tags.append("steady-seller")

        if amazon.buy_box_seller_count and amazon.buy_box_seller_count <= 2:
            tags.append("low-competition")
        elif amazon.is_amazon_selling:
            tags.append("amazon-sells")

        if amazon.review_rating and amazon.review_rating >= 4.5:
            tags.append("top-rated")

        if deal.hot_score and deal.hot_score >= 200:
            tags.append("community-hot")

        if deal.discount_percent and deal.discount_percent >= 50:
            tags.append("deep-discount")

        if deal.category in ("lego", "toys", "gaming"):
            tags.append(deal.category)

        return tags

    def _build_reasoning(
        self,
        deal: Deal,
        amazon: EnrichedProduct,
        profit: ProfitabilityResult,
        components: ScoreComponents,
        tags: list[str],
    ) -> str:
        """
        Build a concise human-readable explanation for the score.
        This is a deterministic fallback; optionally replaced by AI narrative.
        """
        parts = []

        # ROI statement
        if profit.roi_percent >= 40:
            parts.append(f"Strong ROI of {profit.roi_percent:.0f}%")
        elif profit.roi_percent >= 20:
            parts.append(f"Acceptable ROI of {profit.roi_percent:.0f}%")
        else:
            parts.append(f"Thin ROI of {profit.roi_percent:.0f}%")

        # Demand
        if amazon.estimated_monthly_sales:
            parts.append(
                f"~{amazon.estimated_monthly_sales} estimated monthly sales"
                + (f" (BSR #{amazon.sales_rank:,})" if amazon.sales_rank else "")
            )

        # Competition
        if amazon.is_amazon_selling:
            parts.append("Amazon is a direct seller — buy box difficult to win")
        elif amazon.buy_box_seller_count is not None:
            if amazon.buy_box_seller_count <= 2:
                parts.append("Low seller competition")
            else:
                parts.append(f"{amazon.buy_box_seller_count} competing sellers")

        # Reviews
        if amazon.review_count and amazon.review_rating:
            parts.append(f"{amazon.review_count:,} reviews at {amazon.review_rating:.1f}★")

        # Community
        if deal.hot_score and deal.hot_score >= 100:
            parts.append(f"Hot on HotUKDeals ({deal.hot_score}°)")

        # Price stability
        if amazon.lowest_price_30d and amazon.highest_price_30d:
            swing = amazon.highest_price_30d - amazon.lowest_price_30d
            if swing < 2:
                parts.append("Stable Amazon price")
            elif swing > 5:
                parts.append(f"⚠ Price swing of £{swing:.2f} in 30 days — risk of price drop")

        return ". ".join(parts) + "."


def _lerp(value: float, in_min: float, in_max: float, out_min: float, out_max: float) -> float:
    """Linear interpolation — maps value from [in_min, in_max] to [out_min, out_max]."""
    t = (value - in_min) / (in_max - in_min)
    return out_min + t * (out_max - out_min)
